FROM openjdk:8u212-jre
MAINTAINER Sixpence 910584275@qq.com

COPY ./target/febs-monitor-admin-1.3-SNAPSHOT.jar /febs/febs-monitor-admin-1.3-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/febs/febs-monitor-admin-1.3-SNAPSHOT.jar"]